<nav class="menu">
	<ul class="menu__list">
		<li class="menu__item">
			<a href="#" class="menu__link menu__link_purple">Личный кабинет</a>
		</li>
		<li class="menu__item">
			<a href="#" class="menu__link menu__link_green">Раздел 1</a>
		</li>
		<li class="menu__item">
			<a href="#" class="menu__link">Раздел 2</a>
		</li>
		<li class="menu__item">
			<a href="#" class="menu__link menu__link_orange">Раздел 3</a>
		</li>
		<li class="menu__item">
			<a href="#" class="menu__link menu__link_black">Раздел 4</a>
		</li>
		<li class="menu__item">
			<a href="#" class="menu__link menu__link_red">Раздел 5</a>
		</li>
	</ul>
</nav>
